<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="BECOV2">

  <!-- Basic Property -->
  <xacro:property name="leg_length" value="0.045"/>
  <xacro:property name="leg_width" value="0.006"/>
  <xacro:property name="body_size" value="0.1"/>
  <xacro:property name="body_height" value="0.05"/>
  <xacro:property name="body_length" value="0.07"/>
  <xacro:property name="body_width" value="0.047"/>
  <xacro:property name="pipe_length" value="0.06"/> <!-- Updated to match 1cm spacing between bodies -->
  <xacro:property name="pipe_diameter" value="0.01"/>
  <xacro:property name="slider_length" value="0.06"/>
  <xacro:property name="slider_diameter" value="0.005"/>
  <xacro:property name="actuator_range" value="0.06"/>
  <xacro:property name="mass" value="0.5"/>
  <xacro:property name="body_spacing" value="0.02"/>

  <!-- Left Body -->
  <link name="left_body_link">
    <visual>
      <geometry><box size="${body_width} ${body_length} ${body_height}"/></geometry>
      <material name="Blue"/>
    </visual>
    <collision>
      <geometry><box size="${body_width} ${body_length} ${body_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <!-- Left Leg  1 -->
  <link name="left_leg_link">
    <visual>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
      <material name="Red"/>
    </visual>
    <collision>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_leg_joint" type="prismatic">
    <parent link="left_body_link"/>
    <child link="left_leg_link"/>
    <origin xyz="0 -0.015 ${-body_height/2 + 0.017554}"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0.007554" upper="0.025539" effort="10" velocity="0.5"/>
  </joint>

  <!-- Left Leg  2 -->
  <link name="left_leg_link_2">
    <visual>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
      <material name="Red"/>
    </visual>
    <collision>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_leg_joint_2" type="prismatic">
    <parent link="left_body_link"/>
    <child link="left_leg_link_2"/>
    <origin xyz="0 0 ${-body_height/2 + 0.017554}"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0.007554" upper="0.025539" effort="10" velocity="0.5"/>
  </joint>

  <!-- Actuator Pipe -->
  <link name="actuator_pipe_link">
    <visual>
      <geometry><cylinder radius="${pipe_diameter/2}" length="${pipe_length}"/></geometry>
      <origin xyz="${pipe_length/2} 0 0" rpy="0 1.5708 0"/>
      <material name="Gray"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${pipe_diameter/2}" length="${pipe_length}"/></geometry>
      <origin xyz="${pipe_length/2} 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <joint name="pipe_to_left_body_joint" type="fixed">
    <parent link="left_body_link"/>
    <child link="actuator_pipe_link"/>
    <origin xyz="0 0 ${body_height/2}"/>
  </joint>

  <!-- Actuator Slider -->
  <link name="actuator_slider_link">
    <visual>
      <geometry><cylinder radius="${slider_diameter/2}" length="${slider_length}"/></geometry>
      <origin xyz="${slider_length/2} 0 0" rpy="0 1.5708 0"/>
      <material name="Orange"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${slider_diameter/2}" length="${slider_length}"/></geometry>
      <origin xyz="${slider_length/2} 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <joint name="slider_joint" type="prismatic">
    <parent link="actuator_pipe_link"/>
    <child link="actuator_slider_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0.0" upper="${actuator_range}" effort="10" velocity="0.5"/>
  </joint>

  <!-- Right Body -->
  <link name="right_body_link">
    <visual>
      <geometry><box size="${body_width} ${body_length} ${body_height}"/></geometry>
      <material name="Green"/>
    </visual>
    <collision>
      <geometry><box size="${body_width} ${body_length} ${body_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <joint name="slider_to_right_body_joint" type="fixed">
    <parent link="actuator_slider_link"/>
    <child link="right_body_link"/>
    <origin xyz="${slider_length} 0 ${-(body_height/2)}"/>
  </joint>

  <!-- Right Leg -->
  <link name="right_leg_link">
    <visual>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
      <material name="Red"/>
    </visual>
    <collision>
      <geometry><box size="${leg_width} ${leg_width} ${leg_length}"/></geometry>
      <origin xyz="0 0 ${-leg_length/2+0.017554}"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_leg_joint" type="prismatic">
    <parent link="right_body_link"/>
    <child link="right_leg_link"/>
    <origin xyz="0 0 ${-body_height/2 + 0.017554}"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0.007554" upper="0.025539" effort="10" velocity="0.5"/>
</joint>


</robot>
